import { useCallback, useEffect, useState } from "react";
import { Building2, Layers3, Save } from "lucide-react";
import { supabase } from "./supabaseClient";
import "./OrganizationAssignments.css";

type User = { id: string; email: string; profile: { nome: string } | null };
type Option = { id: string; nome: string };
const toggle = (items: string[], id: string) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id];

export function OrganizationAssignments() {
  const [users, setUsers] = useState<User[]>([]); const [companies, setCompanies] = useState<Option[]>([]); const [departments, setDepartments] = useState<Option[]>([]);
  const [selected, setSelected] = useState(""); const [companyIds, setCompanyIds] = useState<string[]>([]); const [departmentIds, setDepartmentIds] = useState<string[]>([]); const [message, setMessage] = useState("");
  const load = useCallback(async () => { if (!supabase) return; const [{ data: userData, error: userError }, { data: companyData, error: companyError }, { data: departmentData, error: departmentError }] = await Promise.all([supabase.functions.invoke("admin-users", { body: { action: "list" } }), supabase.from("empresas").select("id,nome").eq("ativo", true).order("nome"), supabase.from("departamentos").select("id,nome").eq("ativo", true).order("nome")]); if (userError || userData?.error || companyError || departmentError) { setMessage(userData?.error || userError?.message || companyError?.message || departmentError?.message || "Não foi possível carregar vínculos."); return; } setUsers(userData.users ?? []); setCompanies(companyData ?? []); setDepartments(departmentData ?? []); }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!supabase || !selected) { setCompanyIds([]); setDepartmentIds([]); return; } void Promise.all([supabase.from("usuario_empresas").select("empresa_id").eq("usuario_id", selected), supabase.from("usuario_departamentos").select("departamento_id").eq("usuario_id", selected)]).then(([companyResult, departmentResult]) => { if (companyResult.error || departmentResult.error) { setMessage(companyResult.error?.message || departmentResult.error?.message || "Não foi possível carregar vínculos."); return; } setCompanyIds((companyResult.data ?? []).map((item) => item.empresa_id)); setDepartmentIds((departmentResult.data ?? []).map((item) => item.departamento_id)); }); }, [selected]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!supabase || !selected) return; setMessage(""); const [removeCompanies, removeDepartments] = await Promise.all([supabase.from("usuario_empresas").delete().eq("usuario_id", selected), supabase.from("usuario_departamentos").delete().eq("usuario_id", selected)]); if (removeCompanies.error || removeDepartments.error) { setMessage(removeCompanies.error?.message || removeDepartments.error?.message || "Não foi possível atualizar vínculos."); return; } const [addCompanies, addDepartments] = await Promise.all([companyIds.length ? supabase.from("usuario_empresas").insert(companyIds.map((empresa_id) => ({ usuario_id: selected, empresa_id }))) : Promise.resolve({ error: null }), departmentIds.length ? supabase.from("usuario_departamentos").insert(departmentIds.map((departamento_id) => ({ usuario_id: selected, departamento_id }))) : Promise.resolve({ error: null })]); setMessage(addCompanies.error?.message || addDepartments.error?.message || "Vínculos organizacionais atualizados."); };
  return <section className="organization-assignments"><div><p className="eyebrow">ACESSO ORGANIZACIONAL</p><h2>Empresas e departamentos</h2><p>Defina as unidades vinculadas a cada pessoa. Somente administradores podem alterar essas associações.</p></div>{message && <p className="organization-message">{message}</p>}<form onSubmit={save}><label>Usuário<select value={selected} onChange={(event) => setSelected(event.target.value)} required><option value="">Selecione uma pessoa</option>{users.map((user) => <option key={user.id} value={user.id}>{user.profile?.nome || user.email} — {user.email}</option>)}</select></label><div className="assignment-columns"><fieldset><legend><Building2 size={16} />Empresas</legend>{companies.map((company) => <label key={company.id}><input type="checkbox" checked={companyIds.includes(company.id)} onChange={() => setCompanyIds((current) => toggle(current, company.id))} />{company.nome}</label>)}</fieldset><fieldset><legend><Layers3 size={16} />Departamentos</legend>{departments.map((department) => <label key={department.id}><input type="checkbox" checked={departmentIds.includes(department.id)} onChange={() => setDepartmentIds((current) => toggle(current, department.id))} />{department.nome}</label>)}</fieldset></div><button className="primary-button" disabled={!selected} type="submit"><Save size={16} />Salvar vínculos</button></form></section>;
}
