import { useState } from "react";

type Task = { id: string | number; title: string; company: string; category: string; due: string; owner: string; value: number; status: string; priority: string };

export function ApprovalsPage({ tasks, onDecide }: { tasks: Task[]; onDecide: (id: Task["id"], approved: boolean) => void }) {
  const [selected, setSelected] = useState<Task | null>(tasks[0] ?? null);
  const [reason, setReason] = useState("");
  return <section className="product-page"><header><div><p className="eyebrow">FLUXO FINANCEIRO</p><h2>Aprovações</h2><p>Decisões pendentes que exigem registro e responsável.</p></div></header><div className="approvals-layout"><div className="approval-list">{tasks.map((task) => <button key={task.id} className={selected?.id === task.id ? "selected" : ""} onClick={() => { setSelected(task); setReason(""); }}><small>{task.company} · {task.category}</small><strong>{task.title}</strong><span>{task.value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</span></button>)}{tasks.length === 0 && <p className="empty">Não há aprovações pendentes.</p>}</div>{selected && <article className="approval-detail"><p className="eyebrow">EM ANÁLISE</p><h3>{selected.title}</h3><p>{selected.company} · {selected.category} · vencimento {selected.due}</p><strong>{selected.value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</strong><label>Justificativa da decisão<textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Registre a justificativa ou orientação." /></label><div><button className="secondary-button" onClick={() => onDecide(selected.id, false)}>Devolver</button><button className="primary-button" onClick={() => onDecide(selected.id, true)}>Aprovar</button></div></article>}</div></section>;
}

export function CalendarPage({ tasks }: { tasks: Task[] }) {
  const [cursor, setCursor] = useState(new Date()); const days = Array.from({ length: new Date(cursor.getFullYear(), cursor.getMonth() + 1, 0).getDate() }, (_, index) => index + 1);
  return <section className="product-page"><header><div><p className="eyebrow">PLANEJAMENTO</p><h2>Calendário</h2><p>Atividades organizadas por vencimento.</p></div><div><button className="secondary-button" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() - 1, 1))}>‹</button><button className="secondary-button" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1))}>›</button></div></header><div className="calendar-title"><strong>{cursor.toLocaleDateString("pt-BR", { month: "long", year: "numeric" })}</strong></div><div className="calendar-grid monthly">{days.map((day) => <div className="calendar-day" key={day}><strong>{day}</strong>{tasks.filter((task) => task.due.includes(`/${String(cursor.getMonth() + 1).padStart(2, "0")}/`) && task.due.startsWith(`${String(day).padStart(2, "0")}/`)).map((task) => <span className="calendar-task" key={task.id}>{task.title}</span>)}</div>)}</div></section>;
}

export function SettingsPage() { const [saved, setSaved] = useState(false); return <section className="product-page settings-page"><p className="eyebrow">ADMINISTRAÇÃO</p><h2>Configurações</h2><p>Preferências operacionais do ambiente financeiro.</p><label>Fuso horário<select defaultValue="America/Fortaleza"><option>America/Fortaleza</option></select></label><label>Início da semana<select defaultValue="segunda"><option value="segunda">Segunda-feira</option><option value="domingo">Domingo</option></select></label><label className="toggle-setting"><input type="checkbox" defaultChecked />Mostrar notificações no navegador</label><button className="primary-button" onClick={() => setSaved(true)}>Salvar configurações</button>{saved && <p className="notice">Configurações salvas neste dispositivo.</p>}</section>; }

export function ProfilePage() { return <section className="product-page profile-page"><p className="eyebrow">CONTA</p><h2>Meu perfil</h2><div className="profile-card"><div className="avatar">MA</div><div><strong>Marina Alves</strong><p>Financeiro</p></div></div><label>Nome<input defaultValue="Marina Alves" /></label><label>E-mail<input type="email" placeholder="seu-email@empresa.com" /></label><label>Cargo<input defaultValue="Financeiro" /></label><button className="primary-button">Salvar perfil</button></section>; }
