import { useState } from "react";

export type DetailTask = { id: string | number; title: string; company: string; category: string; due: string; owner: string; value: number; status: string };

export function TaskDetail({ task, onClose }: { task: DetailTask; onClose: () => void }) {
  const [subtasks, setSubtasks] = useState<{ id: number; title: string; done: boolean }[]>([]);
  const [comments, setComments] = useState<string[]>([]);
  const [draft, setDraft] = useState("");
  const [subtask, setSubtask] = useState("");
  return <div className="modal-backdrop" role="presentation"><section className="task-detail" role="dialog" aria-modal="true" aria-label="Detalhe da tarefa"><header><div><p className="eyebrow">{task.status}</p><h2>{task.title}</h2><p>{task.company} · {task.category} · Vencimento: {task.due}</p></div><button className="close" onClick={onClose}>×</button></header><div className="detail-meta"><span>Responsável <b>{task.owner}</b></span><span>Valor <b>{task.value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</b></span></div><section><h3>Subtarefas</h3>{subtasks.map((item) => <label className="subtask" key={item.id}><input type="checkbox" checked={item.done} onChange={() => setSubtasks((items) => items.map((current) => current.id === item.id ? { ...current, done: !current.done } : current))} />{item.title}</label>)}<form className="inline-form" onSubmit={(event) => { event.preventDefault(); if (subtask.trim()) { setSubtasks((items) => [...items, { id: Date.now(), title: subtask.trim(), done: false }]); setSubtask(""); } }}><input value={subtask} onChange={(event) => setSubtask(event.target.value)} placeholder="Adicionar subtarefa" /><button className="secondary-button">Adicionar</button></form></section><section><h3>Comentários</h3>{comments.map((comment, index) => <p className="comment" key={`${comment}-${index}`}>{comment}</p>)}<form className="inline-form" onSubmit={(event) => { event.preventDefault(); if (draft.trim()) { setComments((items) => [...items, draft.trim()]); setDraft(""); } }}><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Escreva um comentário" /><button className="primary-button">Enviar</button></form></section><section><h3>Anexos</h3><p className="empty">O envio será disponibilizado ao conectar esta tarefa ao registro persistente.</p></section></section></div>;
}
